server:
  port: 8080
  host: 0.0.0.0
  sockets:
    - name: "secured"
      port: 8443
      # Initial TLS setup is being replaced by certs downloaded from OCI by scheduled task
      tls:
        client-auth: "REQUIRE"
        trust:
          keystore:
            passphrase: "password"
            trust-store: true
            resource:
              resource-path: "different-initial-server.p12"
        private-key:
          keystore:
            passphrase: "password"
            resource:
              resource-path: "different-initial-server.p12"

security:
  mtls-reload:
    # Download mTls context each 10 seconds
    reload-cron: 0/10 * * * * ? *
    # Each OCI Vault has public crypto and management endpoints
    vault-crypto-endpoint: https://bjqkhfbuaaaao-crypto.kms.eu-frankfurt-1.oraclecloud.com
    # Certification Authority in OCI we have signed rotated certificates with
    ca-ocid: ocid1.certificateauthority.oc1.eu-frankfurt-1.amaaaaaarxor3daapterg4ao3r5xdsovhe6tcwxoo5rmukkzcjdupk52rq5a
    server:
      cert-ocid: ocid1.certificate.oc1.eu-frankfurt-1.amaaaaaarxor3daa4onn6cc72zfs72cpwy2ixtsfcfu6ect6hyi65yigo7ca;
      key-ocid: ocid1.key.oc1.eu-frankfurt-1.bjqkhfbuaaaao.abtheljt2wamixp4xbk7mhxvf2mq4us7bhdu7fm6dy4sfkh6w52kdzg6ltma
      key-pass: password
    client:
      cert-ocid: ocid1.certificate.oc1.eu-frankfurt-1.amaaaaaarxor3daa65nneicancdjusua4vet43hkhnsntp74womxre3td4uq;
      key-ocid: ocid1.key.oc1.eu-frankfurt-1.bjqkhfbuaaaao.abtheljsnmfad52ttrxtpu35ac5foje7ddlzq7wbyv7ke23rhoqkfnza5epq
      key-pass: password


