server:
  port: 8080
  host: 0.0.0.0
  sockets:
    - name: "secured"
      port: 8443
      # Initial TLS setup is being replaced by certs downloaded from OCI by scheduled task
      tls:
        client-auth: "REQUIRE"
        trust:
          keystore:
            passphrase: "password"
            trust-store: true
            resource:
              resource-path: "different-initial-server.p12"
        private-key:
          keystore:
            passphrase: "password"
            resource:
              resource-path: "different-initial-server.p12"

security:
  mtls-reload:
    # Download mTls context each 10 seconds
    reload-cron: 0/30 * * * * ? *
    # Each OCI Vault has public crypto and management endpoints
    vault-crypto-endpoint: ${VAULT_CRYPTO_ENDPOINT}
    # Certification Authority in OCI we have signed rotated certificates with
    ca-ocid: ${CA_OCID}
    server:
      cert-ocid: ${SERVER_CERT_OCID}
      key-ocid: ${SERVER_KEY_OCID}
      key-pass: password
    client:
      cert-ocid: ${CLIENT_CERT_OCID}
      key-ocid: ${CLIENT_KEY_OCID}
      key-pass: password